"""Add relationship for measurements

Revision ID: 73e74ad01bbb
Revises: 74aea322df3a
Create Date: 2026-08-24 19:26:36.313816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73e74ad01bbb"
down_revision: Union[str, Sequence[str], None] = "74aea322df3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

order_status_enum = sa.Enum(
"RECEIVED", "CUTTING", "SEWING", "FINISHING", "READY",
    name="order_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "CREATE TYPE order_status AS ENUM "
        "('RECEIVED', 'CUTTING', 'SEWING', 'FINISHING', 'READY')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("price", sa.Integer(), nullable=False))
    op.add_column("orders", sa.Column("delivery", sa.Date(), nullable=True))
    op.add_column("orders", sa.Column("deposit", sa.Integer(), nullable=False))
    op.add_column(
        "orders",
        sa.Column(
            "status",
            sa.Enum(
                "received", "cutting", "sewing", "finishing", "ready",
                name="order_status",
                create_type=False,  # tell SQLAlchemy not to try creating it again
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "orders", sa.Column("clothing_type", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("fabric_type", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("fabric_color", sa.String(length=255), nullable=True)
    )
    op.add_column("orders", sa.Column("lining", sa.String(length=255), nullable=True))
    op.add_column("orders", sa.Column("client_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "orders", "clients", ["client_id"], ["id"], ondelete="CASCADE"
    )
    op.create_check_constraint(
        "check_deposit_range", "orders", "deposit >= 0 AND deposit <= 100"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_deposit_range", "orders", type_="check")
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "client_id")
    op.drop_column("orders", "lining")
    op.drop_column("orders", "fabric_color")
    op.drop_column("orders", "fabric_type")
    op.drop_column("orders", "clothing_type")
    op.drop_column("orders", "status")
    op.drop_column("orders", "deposit")
    op.drop_column("orders", "delivery")
    op.drop_column("orders", "price")
    
    op.execute("DROP TYPE order_status")
    
    order_status_enum.drop(op.get_bind(), checkfirst=True)
    
    # ### end Alembic commands ###
